"""Generate Sieve scripts from consolidated filters."""

import logging
from typing import List, Optional, Set

from src.models.filter_models import (
    ConsolidatedFilter, ConditionGroup, FilterCondition, FilterAction,
    ConditionType, Operator, ActionType, LogicType, empty_value_problem,
    operator_mismatch_problem,
)

logger = logging.getLogger(__name__)

# Section markers for coexistence with user's custom Sieve rules
SECTION_BEGIN = "# === BEGIN ProtonFusion ==="
SECTION_END = "# === END ProtonFusion ==="

# Sieve extensions needed for various features
EXTENSION_MAP = {
    ActionType.MOVE_TO: "fileinto",
    ActionType.LABEL: "fileinto",  # Labels use fileinto in ProtonMail
    ActionType.TRASH: "fileinto",  # fileinto "trash", never discard
    ActionType.MARK_READ: "imap4flags",
    ActionType.STAR: "imap4flags",
    ActionType.ARCHIVE: "fileinto",
}


# Proton's Sieve name for the Trash folder (Proton's Sieve docs and
# ProtonMail/sieve.js both write `fileinto "trash";`).
TRASH_FOLDER = "trash"

# Proton's Sieve name for the Archive folder, as ProtonMail/sieve.js writes
# it (test/fixtures/archive.js). Older versions wrote "Archive"; the rule
# comparison treats the two as the same action (see sieve_rules).
ARCHIVE_FOLDER = "archive"


# The wizard's "has attachment" condition, exactly as Proton's own
# wizard-to-Sieve translator writes it: ProtonMail/sieve.js,
# src/constants.js TEST_NODES.attachment = {Type: 'Exists', Headers:
# ['X-Attached']}, used by toTree.js buildCondition for 'attachments'.
# `exists` is a base RFC 5228 test (section 5.5), so it needs no require.
ATTACHMENT_TEST = 'exists "X-Attached"'


class SieveGenerationError(ValueError):
    """Raised when a filter cannot be written into the ProtonFusion section safely."""


# Characters with special meaning in a :matches pattern (RFC 5228 section
# 2.7.1): "*" and "?" are wildcards and backslash escapes the next character.
_MATCH_SPECIAL = ("\\", "*", "?")


def escape_match_literal(value: str) -> str:
    """Escape a literal value so a :matches pattern matches it verbatim.

    Used for begins-with / ends-with, whose values are plain text that the
    generator wraps in a "*" wildcard. Without this, a "*" or "?" typed in the
    value would act as a wildcard. The result still needs the usual Sieve
    string escaping when it is written into a quoted string.
    """
    out = []
    for ch in value:
        if ch in _MATCH_SPECIAL:
            out.append("\\")
        out.append(ch)
    return "".join(out)


def unescape_match_literal(pattern: str) -> Optional[str]:
    """Inverse of escape_match_literal, or None if the pattern has a live wildcard.

    A trailing lone backslash is kept as a literal backslash, matching how
    Sieve implementations treat it.
    """
    out = []
    i = 0
    while i < len(pattern):
        ch = pattern[i]
        if ch == "\\" and i + 1 < len(pattern):
            out.append(pattern[i + 1])
            i += 2
            continue
        if ch in ("*", "?"):
            return None
        out.append(ch)
        i += 1
    return "".join(out)


class SieveGenerator:
    """Generate Sieve scripts from consolidated filters."""

    def generate(self, filters: List[ConsolidatedFilter]) -> str:
        """Generate a complete Sieve script from consolidated filters."""
        lines = []

        for f in filters:
            self._check_no_section_markers(f)
            self._check_has_conditions(f)

        # Collect required extensions
        extensions = self._collect_extensions(filters)

        # Generate require statement
        if extensions:
            ext_list = ", ".join(f'"{ext}"' for ext in sorted(extensions))
            lines.append(f"require [{ext_list}];")
            lines.append("")

        # Generate header comment
        lines.append("# ProtonFusion - Filter Consolidation")
        lines.append(f"# Generated by ProtonFusion v0.1.0")
        lines.append(f"# Total rules: {len(filters)}")
        lines.append("")

        # Generate rules
        first = True
        for i, f in enumerate(filters):
            if not first:
                lines.append("")

            # Add comment with source filter info
            if f.source_filters:
                if f.filter_count > 1:
                    lines.append(f"# {self._comment_text(f.name)}")
                    sources = ", ".join(f.source_filters[:5])
                    lines.append(f"# Source filters: {self._comment_text(sources)}")
                    if len(f.source_filters) > 5:
                        lines.append(f"#   ... and {len(f.source_filters) - 5} more")
                else:
                    lines.append(f"# {self._comment_text(f.source_filters[0])}")

            # Generate the rule
            condition_str = self._generate_conditions(f)
            action_lines = self._generate_actions(f)

            # _check_has_conditions guarantees a test, so every rule is an if
            lines.append(f"if {condition_str} {{")
            for action_line in action_lines:
                lines.append(f"    {action_line}")
            lines.append("}")

            first = False

        # Final newline
        lines.append("")

        script = "\n".join(lines)
        logger.info("Generated Sieve script: %d lines, %d rules", len(lines), len(filters))
        return script

    @staticmethod
    def _check_no_section_markers(f: ConsolidatedFilter) -> None:
        """Refuse a filter whose text contains a ProtonFusion section marker.

        merge_with_existing and extract_section find the section with a plain
        substring search, so a marker inside a value, folder or filter name
        would end (or start) the section early on the next sync and corrupt
        the merge. Only the user's own filter text can do this, so a clear
        refusal is enough.
        """
        texts = [f.name, *f.source_filters]
        for group in f.condition_groups:
            for cond in group.conditions:
                texts.extend(cond.keys)
        for action in f.actions:
            texts.extend(str(v) for v in action.parameters.values())
        for text in texts:
            for marker in (SECTION_BEGIN, SECTION_END):
                if marker in text:
                    # A consolidated rule's name is synthetic; name the UI filters too
                    origin = f.name if f.source_filters in ([], [f.name]) else (
                        f"{f.name} (from {', '.join(f.source_filters)})")
                    raise SieveGenerationError(
                        f"Filter {origin!r} contains the ProtonFusion section marker "
                        f"{marker!r}, which would corrupt the Sieve section on the next "
                        "sync. Rename or edit that filter in ProtonMail and back up again."
                    )

    @staticmethod
    def _check_has_conditions(f: ConsolidatedFilter) -> None:
        """Refuse a rule that would run its actions on every message.

        A rule with no condition groups, or with a group that has no
        conditions (an original filter with none, which as one branch of an
        OR matches everything), would become top-level actions or an always
        true test. With a Trash or folder action that moves all incoming
        mail. A filter normally has conditions, so this means one was lost
        upstream (for example, dropped as unreadable); refuse rather than
        widen the rule to all mail.
        """
        if f.condition_groups and all(group.conditions for group in f.condition_groups):
            return
        origin = f.name if f.source_filters in ([], [f.name]) else (
            f"{f.name} (from {', '.join(f.source_filters)})")
        raise SieveGenerationError(
            f"Filter {origin!r} has no conditions, so its actions would apply to "
            "every message. Refusing to generate it. Check the filter in ProtonMail "
            "and back up again, or exclude it."
        )

    @staticmethod
    def _comment_text(text: str) -> str:
        """Flatten line breaks so a filter name cannot escape its # comment line."""
        return " ".join(text.splitlines())

    def _collect_extensions(self, filters: List[ConsolidatedFilter]) -> Set[str]:
        """Determine which Sieve extensions are needed."""
        extensions = set()

        for f in filters:
            for action in f.actions:
                ext = EXTENSION_MAP.get(action.type)
                if ext:
                    extensions.add(ext)

        return extensions

    def _generate_conditions(self, f: ConsolidatedFilter) -> str:
        """Generate the Sieve condition expression from condition groups.

        Every group has at least one condition (see _check_has_conditions).
        """
        parts = [self._generate_group(group) for group in f.condition_groups]
        if len(parts) == 1:
            return parts[0]

        # Multiple groups - OR them together (any group matching triggers action)
        inner = ",\n    ".join(parts)
        return f"anyof (\n    {inner}\n)"

    def _generate_group(self, group: ConditionGroup) -> str:
        """Generate conditions for a single, non-empty ConditionGroup."""
        parts = [self._condition_to_sieve(cond) for cond in group.conditions]
        if len(parts) == 1:
            return parts[0]

        joiner = "anyof" if group.logic == LogicType.OR else "allof"
        inner = ",\n        ".join(parts)
        return f"{joiner} (\n        {inner}\n    )"

    def _condition_to_sieve(self, cond: FilterCondition) -> str:
        """Convert a single condition to Sieve syntax.

        Raises SieveGenerationError for an empty value, which would match
        every message (the model flags such a filter incomplete, so this
        only fires for a condition built some other way).
        """
        problem = operator_mismatch_problem(cond) or empty_value_problem(cond)
        if problem:
            raise SieveGenerationError(
                f"Condition {cond.type.value} {cond.operator.value}: {problem}. "
                "It has no Sieve form that would not widen the rule; refusing to generate it."
            )
        comparator = self._operator_to_sieve(cond.operator)

        # A key list comes only from an explicit values list (wizard chips,
        # or filters merged by consolidation). A single value is one literal
        # even if it contains ", " or "|": a key list is an OR, so splitting
        # text would widen the rule.
        values = cond.keys

        # begins-with / ends-with become a :matches pattern around the literal
        # value, so the value's own wildcard characters must be escaped first.
        if cond.operator == Operator.STARTS_WITH:
            values = [escape_match_literal(v) + "*" for v in values]
        elif cond.operator == Operator.ENDS_WITH:
            values = ["*" + escape_match_literal(v) for v in values]

        if len(values) == 1:
            value_str = f'"{self._escape_sieve(values[0])}"'
        else:
            escaped = [f'"{self._escape_sieve(v)}"' for v in values]
            value_str = "[" + ", ".join(escaped) + "]"

        if cond.type == ConditionType.SENDER:
            return f'address {comparator} "From" {value_str}'
        elif cond.type == ConditionType.RECIPIENT:
            return f'address {comparator} ["To", "Cc", "Bcc"] {value_str}'
        elif cond.type == ConditionType.SUBJECT:
            return f'header {comparator} "Subject" {value_str}'
        elif cond.type == ConditionType.ATTACHMENTS:
            return ATTACHMENT_TEST
        elif cond.type == ConditionType.HEADER:
            return f'header {comparator} "X-Custom" {value_str}'

        return f'header {comparator} "From" {value_str}'

    def _operator_to_sieve(self, op: Operator) -> str:
        """Convert operator to Sieve comparator."""
        mapping = {
            Operator.CONTAINS: ":contains",
            Operator.IS: ":is",
            Operator.MATCHES: ":matches",      # value is the user's own pattern
            Operator.STARTS_WITH: ":matches",  # value* (see _condition_to_sieve)
            Operator.ENDS_WITH: ":matches",    # *value
        }
        # HAS is only valid for attachments, which uses no comparator
        return mapping.get(op, "")

    def _generate_actions(self, f: ConsolidatedFilter) -> List[str]:
        """Generate Sieve action statements."""
        lines = []

        for action in f.actions:
            if action.type == ActionType.MOVE_TO:
                folder = action.parameters.get("folder", "INBOX")
                lines.append(f'fileinto "{self._escape_sieve(folder)}";')
            elif action.type == ActionType.LABEL:
                label = action.parameters.get("label", action.parameters.get("folder", ""))
                if label:
                    lines.append(f'fileinto "{self._escape_sieve(label)}";')
            elif action.type == ActionType.MARK_READ:
                lines.append('addflag "\\\\Seen";')
            elif action.type == ActionType.STAR:
                lines.append('addflag "\\\\Flagged";')
            elif action.type == ActionType.ARCHIVE:
                lines.append(f'fileinto "{ARCHIVE_FOLDER}";')
            elif action.type == ActionType.TRASH:
                # Proton: discard deletes "immediately and permanently";
                # a Trash move is `fileinto "trash";` and stays recoverable.
                lines.append(f'fileinto "{TRASH_FOLDER}";')

        if not lines:
            lines.append("keep;")

        return lines

    def _escape_sieve(self, value: str) -> str:
        """Escape special characters for Sieve strings."""
        return value.replace("\\", "\\\\").replace('"', '\\"')

    @staticmethod
    def parse_require_extensions(script: str) -> Set[str]:
        """Extension names from every require in a Sieve script.

        Uses the Sieve tokenizer, so `require "x";` and a require list split
        over lines are both read. Raises SieveParseError if the script does
        not parse.
        """
        # Imported here: sieve_rules imports this module at load time
        from src.generator.sieve_rules import require_extensions
        return require_extensions(script)

    @staticmethod
    def strip_require_lines(script: str) -> str:
        """Remove every require command from a Sieve script, keeping the rest as written.

        Raises SieveParseError if the script does not parse.
        """
        from src.generator.sieve_rules import strip_requires
        return strip_requires(script)

    @staticmethod
    def wrap_with_markers(script: str) -> str:
        """Wrap a script's rules (after stripping require) in section markers."""
        stripped = SieveGenerator.strip_require_lines(script)
        # Remove leading/trailing blank lines
        stripped = stripped.strip("\n")
        return f"{SECTION_BEGIN}\n{stripped}\n{SECTION_END}"

    @staticmethod
    def merge_with_existing(generated_script: str, existing_script: str) -> str:
        """Merge a generated ProtonFusion script with an existing Sieve script.

        Preserves user rules outside the ProtonFusion section markers, in their
        original position relative to the section: content above the section
        stays above it and content below stays below. Sieve evaluates top to
        bottom, so moving a user rule across the section changes behaviour (a
        user ``keep; stop;`` exception above the section stops protecting mail
        once it runs after the section's ``discard``).

        If the existing script has no markers, all of it is treated as user
        content and placed after the new section (there is no prior position to
        preserve).

        Deduplicates require extensions from every part into a single sorted
        require statement at the top.

        Raises SieveParseError if either script does not parse. The result
        should still be checked with sieve_rules.validate_script before it
        is uploaded.
        """
        if not existing_script or not existing_script.strip():
            existing_script = ""

        begin_idx = existing_script.find(SECTION_BEGIN)
        end_idx = existing_script.find(SECTION_END, begin_idx + 1) if begin_idx != -1 else -1

        if begin_idx != -1 and end_idx != -1:
            # Previous ProtonFusion section exists: replace it in place.
            user_before = existing_script[:begin_idx]
            user_after = existing_script[end_idx + len(SECTION_END):]
        else:
            # No previous markers: entire existing script is user content.
            user_before = ""
            user_after = existing_script

        # Collect require extensions from all parts
        all_exts = (
            SieveGenerator.parse_require_extensions(generated_script)
            | SieveGenerator.parse_require_extensions(user_before)
            | SieveGenerator.parse_require_extensions(user_after)
        )

        # Strip require from all parts
        gen_rules = SieveGenerator.strip_require_lines(generated_script).strip("\n")
        before_rules = SieveGenerator.strip_require_lines(user_before).strip()
        after_rules = SieveGenerator.strip_require_lines(user_after).strip()

        # Build final script
        parts = []
        if all_exts:
            ext_list = ", ".join(f'"{e}"' for e in sorted(all_exts))
            parts.append(f"require [{ext_list}];")
            parts.append("")
        if before_rules:
            parts.append(before_rules)
            parts.append("")
        parts.append(SECTION_BEGIN)
        parts.append(gen_rules)
        parts.append(SECTION_END)
        if after_rules:
            parts.append("")
            parts.append(after_rules)
        parts.append("")
        return "\n".join(parts)
